/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuSlugPublicIdRouteImport } from './routes/menu.$slug.$publicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSlugPublicIdRoute = MenuSlugPublicIdRouteImport.update({
  id: '/menu/$slug/$publicId',
  path: '/menu/$slug/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu/$slug/$publicId': typeof MenuSlugPublicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu/$slug/$publicId': typeof MenuSlugPublicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menu/$slug/$publicId': typeof MenuSlugPublicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/menu/$slug/$publicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/menu/$slug/$publicId'
  id: '__root__' | '/' | '/menu/$slug/$publicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuSlugPublicIdRoute: typeof MenuSlugPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$slug/$publicId': {
      id: '/menu/$slug/$publicId'
      path: '/menu/$slug/$publicId'
      fullPath: '/menu/$slug/$publicId'
      preLoaderRoute: typeof MenuSlugPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuSlugPublicIdRoute: MenuSlugPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
